"""notebook entries

Revision ID: 371a033d9868
Revises: 645f2ecf91c8
Create Date: 2025-08-11 12:32:36.720147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '371a033d9868'
down_revision: Union[str, None] = '645f2ecf91c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notebook_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('mood', sa.Enum('good', 'ok', 'bad', name='mood_enum'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notebook_entries_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notebook_entries')),
    sa.UniqueConstraint('user_id', 'entry_date', name='uq_notebook_user_date')
    )
    op.create_index(op.f('ix_notebook_entries_entry_date'), 'notebook_entries', ['entry_date'], unique=False)
    op.create_index(op.f('ix_notebook_entries_user_id'), 'notebook_entries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notebook_entries_user_id'), table_name='notebook_entries')
    op.drop_index(op.f('ix_notebook_entries_entry_date'), table_name='notebook_entries')
    op.drop_table('notebook_entries')
    # ### end Alembic commands ###
