"""courses + course_progress

Revision ID: d72e4900f28c
Revises: 371a033d9868
Create Date: 2025-08-12 16:29:24.933945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd72e4900f28c'
down_revision: Union[str, None] = '371a033d9868'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('storage_key', sa.String(length=512), nullable=False))
    op.add_column('courses', sa.Column('pdf_pages', sa.Integer(), nullable=True))
    op.add_column('courses', sa.Column('version', sa.Integer(), nullable=False))
    op.alter_column('courses', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('courses_id_seq'::regclass)"))
    op.create_unique_constraint(op.f('uq_courses_storage_key'), 'courses', ['storage_key'])
    op.alter_column('enrollments', 'course_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('enrollments', 'course_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_courses_storage_key'), 'courses', type_='unique')
    op.alter_column('courses', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('courses_id_seq'::regclass)"))
    op.drop_column('courses', 'version')
    op.drop_column('courses', 'pdf_pages')
    op.drop_column('courses', 'storage_key')
    # ### end Alembic commands ###
