"""course steps & progress fix2

Revision ID: d90e06404843
Revises: 54b6621c14fb
Create Date: 2025-08-16 13:57:07.988051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd90e06404843'
down_revision: Union[str, None] = '54b6621c14fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('meditation', 'reading', 'quiz', 'reflection', 'video', 'exercise', name='course_step_type'), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_steps_course_id_courses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_steps')),
    sa.UniqueConstraint('course_id', 'order_index', name='uq_course_step_order')
    )
    op.create_index(op.f('ix_course_steps_course_id'), 'course_steps', ['course_id'], unique=False)
    op.create_index('ix_course_steps_course_order', 'course_steps', ['course_id', 'order_index'], unique=False)
    op.create_table('course_step_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('not_started', 'in_progress', 'completed', name='course_step_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['step_id'], ['course_steps.id'], name=op.f('fk_course_step_progress_step_id_course_steps'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_course_step_progress_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_step_progress')),
    sa.UniqueConstraint('user_id', 'step_id', name='uq_user_step')
    )
    op.create_index(op.f('ix_course_step_progress_step_id'), 'course_step_progress', ['step_id'], unique=False)
    op.create_index(op.f('ix_course_step_progress_user_id'), 'course_step_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_course_step_progress_user_id'), table_name='course_step_progress')
    op.drop_index(op.f('ix_course_step_progress_step_id'), table_name='course_step_progress')
    op.drop_table('course_step_progress')
    op.drop_index('ix_course_steps_course_order', table_name='course_steps')
    op.drop_index(op.f('ix_course_steps_course_id'), table_name='course_steps')
    op.drop_table('course_steps')
    # ### end Alembic commands ###
